public class DataTypeExamples {

    /*
    // Boolean Example:

	//Can be set to:
	//	- true
	//	- false
	//	- null
            
Boolean isWeekend;
isWeekend = false;

// use System.debug() to print to a debug log.
System.debug('isWeekend = ' + isWeekend);

// Date Example - a value that indicates a particular day
Date myDate = Date.newInstance(2019, 7, 22);
System.debug('Todays date is ' + myDate);

// Decimal - A number that includes a decimal point.
// Current fields are automatically assigned the type Decimal.
Decimal cost = 19.99;
System.debug('Cost: ' + cost);

// Doube - A 64-bit number that includes a decimal point.
Double pi = 3.14159;
System.debug('pi is ' + pi);

// Decimal vs Double - You should NEVER use floating point representation (Double)
// to handle monetary calculations, instead use Decimal
Double zeroPointZeroOneDouble = 0.01;
Double doubleSum = 0.0;

for (Integer i = 0; i < 10; i++) {
    doubleSum += zeroPointZeroOneDouble;
}

System.debug('doubleSum ' + doubleSum);

Decimal zeroPointZeroOneDecimal = 0.01;
Decimal decimalSum = 0.0;

for (Integer i = 0; i < 10; i++) {
    decimalSum += zeroPointZeroOneDecimal;
}

System.debug('decimalSum ' + decimalSum);

// Integer - A 32-bit number that does not include a decimal
// Min = -2,147,483,648 & Max = 2,147,483,647
Integer age = 23;

// Long - A 64-bit number that does not inlcude a decimal
Long distanceInInchesToTheMoon = 15130000000L;

// Object
// Object can be converted to another data type
// Account will not be able to be converted
Object obj = 10;
Object acc = new Account(Name = 'Matt');
System.debug('obj: ' + (Integer)obj * 2);

// String - Any set of characters surronded by single quotes.
String s ='The quick brown fox jumped over the lazy dog';

// sObject - Any SF object.
sObject c = new Contact();
sObject myClass = new Class__c();

*/
}